<span class="descriptor">Title:</span> Genetically Improved BarraCUDA
<span class="descriptor">Title:</span> Learning universal computations with spikes
<span class="descriptor">Title:</span> The effect of non-reversibility on inferring rooted phylogenies
<span class="descriptor">Title:</span> Exploitation of the genomic double-strand breaks to reduce the  reproductive power of microorganisms
<span class="descriptor">Title:</span> A possible role for stochastic radiation events in the systematic  disparity between molecular and fossil dates
<span class="descriptor">Title:</span> An integrative statistical model for inferring strain admixture within  clinical Plasmodium falciparum isolates
<span class="descriptor">Title:</span> Tissue fibrosis: a principal evidence for the central role of Misrepairs  in aging
<span class="descriptor">Title:</span> Spike Pattern Structure Influences Efficacy Variability under STDP and  Synaptic Homeostasis
<span class="descriptor">Title:</span> Seasonal states in the evolutionary dynamics of finite populations
<span class="descriptor">Title:</span> Genetic correlations greatly increase mutational robustness and can both  reduce and enhance evolvability
